language: go
go:
  - 1.5
  - 1.6
  - tip
install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
script:
  - go vet ./...
  - test -z "$(golint ./... | tee /dev/stderr)"
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test ./...
